### PR TITLE
Revise for 4.06.0 immutable Strings

### PR DESCRIPTION
**Pull request by orbifx**
Can someone more familiar with To.ml confirm the correctness of these changes? They compile.

### CODE REVIEW

**Comment by sagotch** [comment]
Seems good to me.

**Comment by mackwic** [comment]
Thanks for the PR @orbifx ! This is indeed much needed.

Per this repo policy, and also because you've showed your care for this project, you are now a contributor of To.ml with commit rights ! 👏 

I'll make a PR officially adding you as a contributor, PR that you can review and merge ;)

**Comment by orbifx** [comment]
Thank you 😄

**Comment by damiendoligez** [comment]
Can you tell me when you will make a release that includes this fix? Currently, in OPAM there is no version of To.ml that works with OCaml 4.06.0.

**Pull request merged**
