### PR TITLE
V2 doc

### PR DESCRIPTION
**Pull request by Emm**
Add @since and changelog.

I think we're ready for 2.2.0 with this!

### CODE REVIEW

**Comment by sagotch** [comment]
:+1:

**Comment by mackwic** [comment]
For the next PR, could you push you branch (here `v2_doc`) on this repo, then create the PR from `mackwic:v2_doc` to `mackwic:master`, so that anyone can clone the `mackwic:v2_doc` branch and push on it to contribute ?

I would like to add some details on the Changelog but it's not easy when the PR is done directly from the forked repo.

#### Summary:
1. `git ckeckout -b feature-my-branch`
2. code & commit & sync with `git push origin feature-my-branch`
3. When ready: `git push mackwic feature-my-branch`
4. Go on [this repo's url](https://github.com/mackwic/To.ml) and create the PR directly.

Sorry for this change in the workflow, but PR are really tough when they reference a foreign branch.

**Comment by mackwic** [comment]
All things considered, it's a :+1: for me. Though, I would have liked some more details on the Changelog about what's different between 1.0 and 2.0, and I also would add moar `@since`. :)

Meh. It can wait another PR another time. I don't have much time right now so my planning is rather happy that I can't open-procrastinate on PRs.

**Comment by mackwic** [comment]
Aaaand, I did it again. I continued the work on PR #28 on a branch we can all push on. I close this PR as it's the same commits.

**Pull request closed without merging**
