### PR TITLE
We need to use real cross-platform packaging tool

### PR DESCRIPTION
**Pull request by mackwic**
People seems to be interested by the project, we are grown up now, we need to use real packagers tooling.

This is mostly WIP for now, it need to replace our craftsman Makefile by a `_oasis` and its `_tags` which will produce a shiny `setup.ml` with all the feature we can dream.

### TODO
- [x] basic _oasis compiling the lib
- [x] generate the documentation
- [x] generate test binaries
- [x] test commands
- [x] travis integration
- [x] ocverall integration
- [x] deploying commands (including opam generation, documentation, Makefile, etc.)

### Changes
1. Change all reference from `To.ml` to `toml`, which respect the convention of ocamlfindlib
2. All tests are bundled in the same executable `tests/suite.ml`
3. Documentation doesn't include TomlInternal, as it's an internal module
4. Documentation file is named 'Toml' and not 'Toml-api', which is a convention of oasis 
5. Coverage report are enable on the feature flag `--enable-report` when configuring the project

### CODE REVIEW

**Comment by mackwic** [comment]
Coverage fixed ! :ok_hand: https://coveralls.io/builds/1725964

Time to merge, squash, and prepare for the merge.

**Comment by mackwic** [comment]
Coverage fixed ! :ok_hand: https://coveralls.io/builds/1726037

Documenting a bit, merging with master, squashing, then prepare for the merge of the PR

**Comment by mackwic** [comment]
Good to merge for me. :rocket: 
Can I merge this PR ?

**Comment by sagotch** [comment]
(y)

**Comment by Emm** [comment]
Fine for me.

**Pull request merged**
